### ISSUE TITLE
Conversions not working - <title>404 Not Found</title> 

### ISSUE THREAD

**Issue by nodecentral** [zelon88/HRConvert2#36]
HI

I’ve installed the HRconvert2 docker instance, and while I can upload files, any attempt to convert something returns the chosen format with an additional html type added - e.g if I upload `file.doc’ to convert to a pdf, it will return a file called `file.pdf.html` which include the following..
````
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at 192.168.100.134 Port 8085</address>
</body></html>
````
Looking in the config.php, I have the following for the URL to use
````
//Put the URL used to access HRConvert here
$URL = 'localhost:8085';
````
My docker compose is..
````
version: "3"
services:
  app:
    image: dwaaan/hrconvert2-docker:latest
    restart: unless-stopped
    ports:
      - 8085:80
    volumes:
      - /share/Container/hrconvert2/config.php:/var/www/html/HRProprietary/HRConvert2/config.php
````
Any ideas what to do to fix it  ?
